#if !canImport(ObjectiveC)
import XCTest

extension DiceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DiceTests = [
        ("testRolling", testRolling),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DiceTests.__allTests__DiceTests),
    ]
}
#endif
