#if !canImport(ObjectiveC)
import XCTest

extension DiceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DiceTests = [
        ("testRollCount", testRollCount),
        ("testSpecification", testSpecification),
    ]
}

extension InterfaceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InterfaceTests = [
        ("testInvalidSpecification", testInvalidSpecification),
        ("testRolling", testRolling),
        ("testRollingSpec", testRollingSpec),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DiceTests.__allTests__DiceTests),
        testCase(InterfaceTests.__allTests__InterfaceTests),
    ]
}
#endif
